---
- name: Warn user if using insecure SSL key pair.
  debug:
    msg: >
      ***SECURITY RISK***: You are currently using the included/default SSL key
      pair. Please generate your own secure key pair if using this playbook for
      any kind of production purposes!
  when: "logstash_ssl_certificate_file.find('-example.crt') != -1"

- name: Ensure Logstash SSL key pair directory exists.
  file:
    path: "{{ logstash_ssl_dir }}"
    state: directory
  when: logstash_ssl_key_file

- name: Copy SSL key and cert for logstash-forwarder.
  copy:
    src: "{{ item }}"
    dest: "{{ logstash_ssl_dir }}/{{ item | basename }}"
    mode: 0644
  with_items:
    - "{{ logstash_ssl_key_file }}"
    - "{{ logstash_ssl_certificate_file }}"
  notify: restart logstash
  when: logstash_ssl_key_file
